# 配置 Eureka 端口
server:
  port: 8080

spring:
  application:
    name: eureka_one

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    # 调用其它服务 false
    fetch-registry: false
    #  进行自我注册  false
    register-with-eureka: true
  instance:
    hostname: localhost