# \u914D\u7F6Eeureka\u7AEF\u53E3
server:
  port: 8080

spring:
  application:
    name: eureka-one

eureka:
  client:
    service-url:
      defaultZone: http://www.meureka.two.com:8081/eureka,http://www.meureka.three.com:8082/eureka
    # \u8C03\u7528\u5176\u5B83\u670D\u52A1 false
    fetch-registry: false
    # \u81EA\u6211\u6CE8\u518Cfalse
    register-with-eureka: false
    #register-with-eureka: true
  instance:
    hostname: localhost