server:
  port: 7575
spring:
  application:
    name: m-comsumer-feign

eureka:
  client:
    service-url:
      defaultZone: http://www.meureka.one.com:8080/eureka,http://www.meureka.three.com:8082/eureka,http://www.meureka.one.com:8081/eureka

# \u670D\u52A1\u8C03\u7528\u51FA\u73B0\u4E86\u95EE\u9898\u4E4B\u540E\u5982\u679C\u8981\u9694\u79BB\uFF0C\u964D\u7EA7\uFF0C\u9700\u8981\u5F00\u542Fhystrix
feign:
  hystrix:
    enabled: true

hystrix:
  commond:
    default:
      execution:
        isolation:
          strategy: THREAD  \u7EBF\u7A0B\u9694\u79BB
#          strategy: SEMAPHORE  # \u4FE1\u53F7\u9694\u79BB

          thread:
            timeoutInMilliseconds: 2000
      timeout:
        enable: false # \u9ED8\u8BA4\u662Ftrue \u65E0\u8D85\u65F6\u8C03\u7528
    circuitBreaker:
      # \u9ED8\u8BA4\u5F00\u6237\u65AD\u8DEF\u5668
      enable: true
      #\u7194\u65AD\u5668\u5F00\u6253\u524D\uFF0C\u5931\u8D25\u7684\u6B21\u6570
      requestVolumeThreshold: 2
      #\u7194\u65AD\u5668\u6253\u5F00\u7684\u6301\u7EED\u65F6\u95F4\uFF0C\u5230\u65F6\u95F4\u540E\uFF0C\u4F1A\u81EA\u52A8\u7684\u56DE\u5230\u534A\u5F00\u72B6\u6001
      sleepWindowInMilliseconds: 5000
